### ISSUE TITLE
Build not getting successfull

### ISSUE THREAD

**Issue by gourav-kandoria** [unikraft-cloud/examples#132]
**While trying to build and deploy on WSL getting the following error.**

root@LAPTOP-J1M9RJAU:~/examples/http-python3.12-flask3.0# kraft cloud deploy -p 443:8080 -M 512 --metro sin0 .
 i  use --as=kraftfile-runtime to skip this prompt in the future
Caught panic:

checked path: $XDG_RUNTIME_DIR

Restoring terminal...

goroutine 303 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).recoverFromPanic(0xc0001feb40)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.2/tea.go:705 +0x91
panic({0x1e63bc0?, 0xc000b1c2b8?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/testcontainers/testcontainers-go/internal/core.MustExtractDockerHost.func1()
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/internal/core/docker_host.go:91 +0x66
sync.(*Once).doSlow(0xc000891c30?, 0xc000891c80?)
        /usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
github.com/testcontainers/testcontainers-go/internal/core.MustExtractDockerHost({0x2592198?, 0x37abcc0?})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/internal/core/docker_host.go:88 +0x58
github.com/testcontainers/testcontainers-go/internal/core.NewClient({0x2592198, 0x37abcc0}, {0x0, 0x0, 0x0?})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/internal/core/client.go:17 +0x88
github.com/testcontainers/testcontainers-go.NewDockerClientWithOpts({0x2592198, 0x37abcc0}, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/docker_client.go:117 +0x71
github.com/testcontainers/testcontainers-go.NewDockerProvider({0xc0004e2320, 0x2, 0x21c1d7f?})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/provider.go:143 +0x10f
github.com/testcontainers/testcontainers-go.ProviderType.GetProvider(0x0, {0xc000892e28, 0x1, 0x586d1a?})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/provider.go:114 +0x3e5
github.com/testcontainers/testcontainers-go.GenericContainer({_, _}, {{{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.0/generic.go:59 +0x139
kraftkit.sh/initrd.(*dockerfile).Build(0xc0003a5680, {0x25920b8, 0xc00068b620})
        /__w/kraftkit/kraftkit/initrd/dockerfile.go:283 +0xad9
kraftkit.sh/internal/cli/kraft/utils.BuildRootfs.func1({0x25920b8?, 0xc00068b620?})
        /__w/kraftkit/kraftkit/internal/cli/kraft/utils/rootfs.go:55 +0x63
kraftkit.sh/tui/processtree.(*ProcessTree).Init.(*ProcessTree).waitForProcessCmd.func2()
        /__w/kraftkit/kraftkit/tui/processtree/processtree.go:334 +0x11a
github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.2/tea.go:324 +0x86
created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1 in goroutine 320
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.2/tea.go:318 +0x139
 E  could not prepare deployment: could not package: could not package: could not build rootfs: program was killed: context canceled

**These are WSL Details**

root@LAPTOP-J1M9RJAU:~/examples/http-python3.12-flask3.0# uname -a
Linux LAPTOP-J1M9RJAU 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 GNU/Linux

**Comment by gourav-kandoria** [comment]
Running Docker Service alongside solves the issue
